/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent any

    options {
        timestamps()
    }

    stages {
        stage('Build') {
            steps {
                echo 'start building image'
                dir('docker') {
                    sh 'sudo docker build -t app .'
                }
            }
        }
    }
}
