pipeline {
    agent any

    options {
        timestamps()
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Nobls/Jenkins.git'
            }
        }
        stage('Build') {
            steps {
                /* groovylint-disable-next-line NoDef, VariableTypeRequired */
                def changes = sh(returnStdout: true, script: 'git status --short')

                /* groovylint-disable-next-line UnnecessaryGetter */
                if (changes.trim().isEmpty()) {
                    echo 'start building image'
                    /* groovylint-disable-next-line NestedBlockDepth */
                    dir('docker') {
                        sh 'docker build -t app .'
                    }
                }
            }
        }
    }
}
